### ISSUE TITLE
(--check-proofs) Invalid model on QF_ABV formula

### ISSUE THREAD

**Issue by wintered** [cvc5/cvc5#8809] opened 2022-05-21 12:09 UTC
[3898889](https://github.com/cvc5/cvc5/commit/38988892041143d7f187af89f0d45126979278e7)
```
$cvc5 -q --check-models --check-proofs bug.smt2 
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::
TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool)  
 at solvers/cvc5/src/smt/check_models.cpp:134. 
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:  
assertion:     (let ((_let_1 (store a b b))) (let ((_let_2 (select a b))) (= (store _let_1 _let_2 _let_2)  
(store _let_1 (bvurem b b) 
(bvadd #b0001000100010001000100010001000100010001000100010001000100010001 b)))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
[1]    4157638 abort      cvc5 -q --check-models --check-proofs bug.smt2
$cat bug.smt2 
(declare-const  a (Array (_ BitVec 64) (_ BitVec 64))) 
(declare-const  b (_ BitVec 64)) 
(assert (= (store (store a b b) (select a b) (select a b)) (store (store a b b) 
        (bvurem b b)(bvadd #x1111111111111111 b)))) 
(check-sat)
```

**Comment by aniemetz** [comment] 2022-08-23 23:25
This might be a duplicate of https://github.com/cvc5/cvc5-projects/issues/320.

**Closed** 2024-04-16 23:33 UTC
