### ISSUE TITLE
Question about minimal unsat core

### ISSUE THREAD

**Issue by alebugariu** [cvc5/cvc5#3023] opened 2019-05-28 14:30 UTC
I am using the option --produce-unsat-cores to obtain the unsat core, but for some examples it is not minimal. Is it possible to obtain the minimal unsat core for a given formula?

Thank you very much,
Alexandra

**Comment by 4tXJ7f** [comment] 2019-05-28 19:53
Unfortunately, CVC4 itself does not support the minimization of unsat cores at this time. Which logic are you interested in?

**Comment by alebugariu** [comment] 2019-05-29 06:52
The formulas are from the string theory.

**Comment by 4tXJ7f** [comment] 2019-06-06 07:19
Sorry about the delayed answer. It is always exciting to of new applications for the theory of strings. If it's possible, I'd be very interested to learn more about your application and if you have a set of benchmarks, we can add them to our set of performance tests.

For the minimal unsat core, I've implemented a prototype [here](https://github.com/4tXJ7f/CVC4/tree/minimalUnsatCores). To produce minimal unsat cores (i.e. irreducible unsat cores) use the option `--minimal-unsat-cores` together with `(set-option :produce-unsat-cores true)`. It is just a simple deletion-based approach for now that is not optimized at all. If you get a chance, please let me know how that works for you.

**Comment by alebugariu** [comment] 2019-06-11 20:57
Thanks a lot for the prototype. I've tried it out on some benchmarks and it works fine, I always got the expected result. I will send you our benchmarks via email by tomorrow.

But I also noticed something, which I'm not sure it's related. For the following formula:
```
(set-option :random-seed 0)
(set-option :produce-models true)
(set-option :produce-unsat-cores true)
(set-info :status unsat)
(declare-fun tmp_str0 () String)
(declare-fun tmp_str1 () String)
(declare-fun t () String)
(declare-fun s () String)
(declare-fun tmp_bool2_fresh () Bool)
(assert (! 
 (and (= (= tmp_str0 tmp_str1) tmp_bool2_fresh) (= (= (str.len tmp_str0) (str.len tmp_str1)) false)) :named a1))
(assert (! 
 (forall ((s1 String) (s2 String) (s3 String) )(let (($x339 (= (str.++ (str.++ s1 s2) s3) s)))
 (=> $x339 (= (= s2 t) tmp_bool2_fresh))))
  :named a2))
(assert (! 
 (let (($x322 (str.contains s t)))
 (let (($x328 (= $x322 false)))
 (not $x328))) :named a0))
(check-sat)

(get-unsat-core)
```
both with and without the ```--minimal-unsat-cores``` option, CVC4 returns as the unsat core a1, which is quite surprising; a1 alone is a satisfiable formula.

**Comment by 4tXJ7f** [comment] 2019-06-11 21:28
It's great to hear that the `--minimal-unsat-cores` option seems to work so far. Which options are you using with the benchmark above and how long does it take for you to generate the unsat core? It seems to take a long time for me. Thanks!

**Comment by alebugariu** [comment] 2019-06-11 21:39
I got an answer immediately, without even setting a timeout. I've just used the ```--strings-exp``` option. I observed this behavior both with the code from the minimalUnsatCore branch and with the 1.7 release version. In both cases I built it from sources, on Mac.

**Comment by alebugariu** [comment] 2019-06-12 15:26
Unfortunately, I can no longer reproduce the behavior that I described. I don't know why, I haven't changed anything, but now the result that I get is as yours (non termination/very long time to solve the formula). I'm sorry for the confusion.

**Comment by 4tXJ7f** [comment] 2019-06-12 18:31
Hm, yes. I tried with a bunch of different CVC4 variants: CVC4 compiled with Clang under Linux, CVC4 compiled with GCC under Linux, and CVC4 compiled on macOS and none of them seemed to terminate on this input. Could it be that you observed the issue on a different problem? Please let me know if you find a way of reproducing the issue.

**Comment by alebugariu** [comment] 2019-07-21 18:25
I couldn't reproduce that issue anymore, I'm really sorry.
I got instead an internal error while trying to get the minimal unsat core for the following formula:
```
(set-option :random-seed 0)
(set-option :produce-models true)
(set-option :produce-unsat-cores true)
(set-info :status unsat)
(declare-fun s () String)
(declare-fun result () String)
(declare-fun s3 () String)
(declare-fun u () String)
(declare-fun s1_fresh () String)
(declare-fun t () String)
(declare-fun s2 () String)
(declare-fun index () Int)
(declare-fun s1 () String)
(assert (! 
 (let (($x138 (= result s)))
 (let (($x139 (= $x138 true)))
 (let (($x1031 (and (= (str.++ (str.++ s1_fresh s2) s3) s) (and (= (str.len s1_fresh) index) (= (= s2 t) true)))))
 (let (($x121 (>= index 0)))
 (let (($x1036 (ite $x121 (and $x1031 (= (str.++ (str.++ s1_fresh u) s3) result)) $x139)))
 (let ((?x118 (str.indexof s t 0)))
 (let (($x120 (= ?x118 index)))
 (and $x120 $x1036)))))))) :named a1))
(assert (! 
 (and (= (str.at s1 0) s1_fresh) (= (str.len s1) 1)) :named a2))
(assert (! 
 (let ((?x115 (str.replace s t u)))
 (let (($x116 (= ?x115 result)))
 (not $x116))) :named a0))
(check-sat)
(get-unsat-core)
```
I used the options: --strings-exp --minimal-unsat-cores --random-seed=0 --tlimit 15000 and I obtained:  unsat
(error "Internal error detected
CVC4::UnsatCore CVC4::SmtEngine::reduceUnsatCore(const CVC4::UnsatCore &)
cvc4/src/smt/smt_engine.cpp:4551: SmtEngine::checkUnsatCore(): could not reduce unsat core due to unknown result.")

Thanks a lot for all your help.

**Comment by ajreynol** [comment] 2023-01-11 15:48
In the current main branch of cvc5, adding `--minimal-unsat-cores` causes cvc5 to time out on the last example.  This can be expected behavior, as minimizing the unsat core relies on satisfiability checks, which themselves may time out.

Also note the error ` could not reduce unsat core due to unknown result.` is now a warning: https://github.com/cvc5/cvc5/blob/main/src/smt/solver_engine.cpp#L1373.

I'm closing this issue, do let us know if there are further questions regarding this feature.

**Closed by ajreynol** 2023-01-11 15:48 UTC
Labels: question
