### ISSUE TITLE
Soundness Issue in QF_ABV

### ISSUE THREAD

**Issue by dylanjwolff** [cvc5/cvc5#5925] opened 2021-02-18 17:07 UTC
Hi,

The following file seems to trigger a soundness issue in CVC4:

[bug.smt2.zip](https://github.com/CVC4/CVC4/files/6004582/bug.smt2.zip)

```
 % cat bug.smt2
(set-logic QF_ABV)
(declare-const a (Array Bool Bool))
(declare-const b Bool)
(declare-const c Bool)
(declare-const d Bool)
(assert (= (store (store ((as const (Array Bool Bool)) true) true false) false false) (store a b c)))
(assert b)
(assert (= d (select a c)))
(assert d)
(check-sat)
 % cvc4 bug.smt2 
sat
% cvc4 bug.smt2 --produce-models
unsat
```
**Command line arguments**: none
**CVC4 version/commit**: CVC4 version 1.9-prerelease [git HEAD a1a2d938]
**Operating system**: Ubuntu

**`configure.sh` options**
`./configure.sh --symfpu`

**`configure.sh` output**
[config_out.txt](https://github.com/CVC4/CVC4/files/6004590/config_out.txt)

**Comment by mpreiner** [comment] 2021-02-18 18:49
Seems to be an issue with the array solver, reduced file:

```
(set-logic QF_A)
(declare-const a (Array Bool Bool))
(assert (= (store a true false) (store (store ((as const (Array Bool Bool)) true) true false) false false)))
(assert (select a false))
(check-sat)
```

**Comment by 4tXJ7f** [comment] 2022-03-01 17:53
This may be a duplicate of #6700, because without `--no-arrays-optimize-linear`, the issue does not occur.

**Comment by ajreynol** [comment] 2022-03-02 22:23
Should we disable `--arrays-optimize-linear` by default? @barrettcw

**Closed** 2022-03-29 06:50 UTC
