### ISSUE TITLE
Fatal failure at cvc5/src/theory/arith/nl/nl_model.cpp:895

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#7919] opened 2022-01-11 06:50 UTC
Commit: [8c18b39](https://github.com/cvc5/cvc5/commit/8c18b3962679ead1c66cfa8118ec93176d8860b6)
OS: Ubuntu 20.04

```
$ cvc5 -q delta.smt2
Fatal failure within bool cvc5::theory::arith::nl::NlModel::simpleCheckModelMsum(const std::map<cvc5::NodeTemplate<true>, cvc5::NodeTemplate<true> >&, bool) at /cvc5/src/theory/arith/nl/nl_model.cpp:895
Check failure

 false

Aborted (core dumped)
$ cat delta.smt2
(declare-fun r () Real)
(declare-fun re () Real)
(declare-fun e () Real)
(assert (and (>= e r) (>= r e) (> 0.0 (/ re e)) (= (sin 1) (/ 0.0 0.0 (- 1 r)))))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-01-12 14:46
I believe this is a duplicate of https://github.com/cvc5/cvc5/issues/4693.

**Closed** 2022-02-24 21:56 UTC
Labels: duplicate
