### ISSUE TITLE
Fatal failure at src/theory/arith/nl/nl_model.cpp:873 

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#8181] opened 2022-02-26 14:45 UTC
Commit: https://github.com/cvc5/cvc5/commit/f051883afa31d9dbe14a5d1ae1c9700cffded3b1
OS: Ubuntu 18.04

```
[580] % cvc5 -q small.smt2
Fatal failure within bool cvc5::theory::arith::nl::NlModel::simpleCheckModelMsum(const std::map<cvc5::NodeTemplate<true>, cvc5::NodeTemplate<true> >&, bool) at /local/suz-local/software/CVC4/src/theory/arith/nl/nl_model.cpp:873
Check failure

 false

Aborted
[581] % cat small.smt2
(declare-fun a () Int)
(declare-fun b () Int)
(assert (> (/ 0.5 (cos 0.5) (/ b (/ (+ 0.5 (ite (= a 0) 0 1)) 0))) 0))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-02-28 14:39
I think this is a duplicate of https://github.com/cvc5/cvc5/issues/4693.

**Closed** 2022-03-01 21:14 UTC
