### ISSUE TITLE
Fatal crash during node building on scrambled Sage2 benchmarks

### ISSUE THREAD

**Issue by hansjoergschurr** [cvc5/cvc5#9744] opened 2023-05-10 21:50 UTC
**Describe the bug**
When I run `cvc5` on some `QF_BV` benchmarks from the Sage2 family, it crashes after a few second with the following error

```
Fatal failure within void cvc5::internal::NodeBuilder::realloc(size_t) a ???/cvc5/src/expr/node_builder.cpp:278
Check failure

 toSize > d_nvMaxChildren
attempt to realloc() a NodeBuilder to a smaller/equal size!
```

affected are the benchmarks 
```
QF_BV/Sage2/bench_1471.smt2
QF_BV/Sage2/bench_13528.smt2
QF_BV/Sage2/bench_16265.smt2
QF_BV/Sage2/bench_16718.smt2
```

I could no immediately reproduce the problem with the original benchmarks.  When the error occurred, the benchmarks were scrambled by the current smt-comp scrambler using the seed 43. 

Attached are the scrambled version of the [benchmark 1471](https://github.com/cvc5/cvc5/files/11446247/sage2_1471.txt) and a 
[partially minimized version](https://github.com/cvc5/cvc5/files/11446249/sage2_1471_min.txt)

**Command line arguments**: None
**cvc5 version/commit**: 94e6d46745250c4bfc934d259299ad25e5fad492
**`configure.sh` options**
`competition --assertions --static --gpl --cln --glpk --auto-download`

**Comment by ajreynol** [comment] 2023-05-11 18:00
I believe this is a duplicate of https://github.com/cvc5/cvc5/issues/9126.

**Closed** 2023-05-16 16:54 UTC
Labels: duplicate
