### ISSUE TITLE
Fatal failure at /src/prop/minisat/core/Solver.cc:1994

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8767] opened 2022-05-13 03:59 UTC
Hi, 
For this instance, cvc5 https://github.com/cvc5/cvc5/commit/36892a5bb9ad1bf2145912700f5998f971bb167a
```
$ cvc5 -i -q delta.smt2
(error "Subexpressions must have the same type:
Equation: (= (select (store (select v 0) 0 0) 0) 0)
Type 1: Real
Type 2: Int
")
Fatal failure within void cvc5::internal::Minisat::Solver::pop() at /root/cvc5/src/prop/minisat/core/Solver.cc:1994
Check failure

 decisionLevel() == 0

Aborted (core dumped)
$ cat delta.smt2
(declare-fun v () (Array Int (Array Int Real)))
(declare-fun va () (Array Int (Array Int Real)))
(push)
(assert (forall ((a (Array Int (Array Int Real)))) (and (= (select va 1) (select va 0)) (forall ((V Int)) (and (distinct va v) (= va (store va 0 (store (select a 0) 0 0))))))))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-05-13 13:18
I believe we've seen similar issues in the past, where this is related to not catching exceptions properly.

**Comment by aniemetz** [comment] 2022-08-23 23:27
This might be a duplicate of https://github.com/cvc5/cvc5-projects/issues/435.

**Closed** 2022-09-12 17:50 UTC
