### ISSUE TITLE
(check-proofs) Fatal failure at src/prop/minisat/core/Solver.cc:1447 

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#8210] opened 2022-03-02 21:23 UTC
Commit: https://github.com/cvc5/cvc5/commit/edfcb4be0617bd28eb9379d8bfe49524ecde3ec1
OS: Ubuntu 18.04

```
[587] % cvc5 -q -i --check-proofs small.smt2
sat
unsat
Fatal failure within void cvc5::Minisat::Solver::removeClausesAboveLevel(cvc5::Minisat::vec<unsigned int>&, int) at /local/suz-local/software/CVC4/src/prop/minisat/core/Solver.cc:1447
Check failure

 !locked(c)

Aborted
[588] % cat small.smt2
(declare-fun a () Bool)
(declare-fun b () Real)
(assert (or a (<= b 0)))
(assert (< b 0))
(check-sat)
(push)
(assert (> b 0))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-03-02 21:24
`--check-proofs` is currently experimental, this is a duplicate of https://github.com/cvc5/cvc5-projects/issues/314.

**Closed** 2022-03-03 04:54 UTC
Labels: duplicate
