### ISSUE TITLE
Invalid model for NRA formula

### ISSUE THREAD

**Issue by rainoftime** [cvc5/cvc5#5773] opened 2021-01-13 13:10 UTC
Hi, for the following formula,
CVC4  b212e6455595
~~~~
(set-logic NRA)
(declare-fun r1 () Real)
(declare-fun r3 () Real)
(declare-fun r4 () Real)
(assert (not (= r1 r4)))
(assert (< 0.0 r3))
(assert (or (not (= 0.0 (/ 1 r3))) (= (* r4 r4) (/ 1 r1))))
(check-sat)
~~~~
~~~~
cvc4 -q -i --check-models delta.out.smt2 
Fatal failure within void CVC4::smt::CheckModels::checkModel(CVC4::smt::Model*, CVC4::context::CDList<CVC4::NodeTemplate<true> >*, bool) at /home/CVC4/src/smt/check_models.cpp:129
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (not (= r1 r4))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped)
~~~~

**Comment by ajreynol** [comment] 2021-01-19 02:48
Caused by `(not (= r1 r4))` not being asserted to arithmetic and model repair falsifying it, theoryof-mode=type works.  We should probably eliminate the model repair stuff altogether as it is subsumed by the nl-cad solver.

**Comment by rainoftime** [comment] 2021-01-20 01:40
~~~~
(set-logic NRA)
(declare-fun r3 () Real)
(declare-fun r6 () Real)
(declare-fun r8 () Real)
(assert (and (= 1 (* r8 r3)) (= 1.0 (/ 1 (+ r8 r6)))))
(check-sat)
~~~~

**Comment by nafur** [comment] 2021-05-18 10:30
These issues have been fixed in the meantime.
The current master (c781d274fbaf6f4b3e419140c5834511d6b7c7a0) yields the following:
```
$ bin/cvc5 --check-models test1.smt2 
Warning : SmtEngine::checkModel(): cannot check simplified assertion : (= (/ 1 0) 1)
sat
$ bin/cvc5 --check-models test2.smt2 
sat
``
I thus close this issue.

**Closed by nafur** 2021-05-18 10:30 UTC
