### ISSUE TITLE
Fix datatype-dump regression test

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5#1649] opened 2018-03-08 18:59 UTC
The following regression test is currently not passing (and disabled): https://github.com/CVC4/CVC4/blob/c6b2e085d4eb2c232a528a96e13fc7b65fd98fea/test/regress/regress0/datatypes/datatype-dump.cvc. Either the expected output needs to be fixed or the output of CVC4.

**Comment by ajreynol** [comment] 2018-03-22 16:06
This was fixed in https://github.com/CVC4/CVC4/pull/1672

**Comment by ajreynol** [comment] 2018-03-30 18:44
Reopened since its breaking nightly regressions.

**Comment by ajreynol** [comment] 2018-03-30 18:44
Mathias is looking into this now.

**Closed** 2021-10-21 01:31 UTC
Labels: bug, minor
