### ISSUE TITLE
(solve-bv-as-int) Fatal failure at /root/cvc5/src/theory/bv/int_blaster.cpp:263

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8411] opened 2022-03-27 15:32 UTC
Hi,
For this instance, cvc5 https://github.com/cvc5/cvc5/commit/c7507cebfa909d6662b7a8635a9dc9e3f2bf801a debug build
```
$ cvc5 --solve-bv-as-int=bitwise -q delta.smt2
Fatal failure within cvc5::Node cvc5::IntBlaster::translateWithChildren(cvc5::Node, const std::vector<cvc5::NodeTemplate<true> >&, std::vector<cvc5::NodeTemplate<true> >&) at /root/cvc5/src/theory/bv/int_blaster.cpp:263
Check failure

 oldKind != kind::BITVECTOR_COMP

Aborted (core dumped)
$ cat delta.smt2
(declare-const x (_ BitVec 1))
(assert (= (_ bv0 1) (bvashr (_ bv1 1) (bvcomp (_ bv0 2) ((_ zero_extend 1) x)))))
(check-sat)
```

**Comment by merlinsun** [comment] 2022-03-28 01:48
Another instance related to `--solve-bv-as-int=bitwise`:
```
# cvc5 case.smt2 --solve-bv-as-int=bitwise -q
Fatal failure within cvc5::Node cvc5::IntBlaster::translateNoChildren(cvc5::Node, std::vector<cvc5::NodeTemplate<true> >&, std::map<cvc5::NodeTemplate<true>, cvc5::NodeTemplate<true> >&) at /root/cvc5/src/theory/bv/int_blaster.cpp:668
Check failure

 original.isVar() || original.isConst() || original.isNullaryOp()

Aborted (core dumped)
# cat case.smt2
(assert (exists ((v String)) (= "" (str.replace_re v re.allchar v))))
(check-sat)
```

**Comment by mpreiner** [comment] 2022-03-28 16:00
First one is duplicate of https://github.com/cvc5/cvc5-projects/issues/417
Second one is duplicate of https://github.com/cvc5/cvc5-projects/issues/416

**Closed by mpreiner** 2022-03-28 16:00 UTC
