### ISSUE TITLE
Cannot use eager bitblasting with pythonic API

### ISSUE THREAD

**Issue by ambiso** [cvc5/cvc5#9918] opened 2023-07-27 13:02 UTC
The following usage of the pythonic API fails:

```py
from cvc5.pythonic import Solver

s = Solver()
s.setOption('bitblast', 'eager')

print(s.check())
```

with the following error:

```
Traceback (most recent call last):
  File "/mnt/mre.py", line 7, in <module>
    print(s.check())
  File "/usr/local/lib/python3.10/dist-packages/cvc5/pythonic/cvc5_pythonic.py", line 5313, in check
    r = CheckSatResult(self.solver.checkSatAssuming(*[a.ast for a in assumptions]))
  File "cvc5.pxi", line 1989, in cvc5_python_base.Solver.checkSatAssuming
RuntimeError: Error in option parsing: Eager bit-blasting currently does not support model generation for the combination of bit-vectors with arrays or uinterpreted functions. Try --bitblast=lazy
```

which I think comes from here:
https://github.com/cvc5/cvc5/blob/cvc5-1.0.5/src/smt/set_defaults.cpp#L271-L283

I would have expected it to succeed, because I believe I am not using any theory at all.

**Command line arguments**: not applicable
**cvc5 version/commit**: cvc5-1.0.5
**Operating system**: Ubuntu 22.04.2 LTS

**`configure.sh` options**  
`./configure.sh --cryptominisat --auto-download --python-bindings`

**`configure.sh` output**
<details>
<summary>output here...</summary>

```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Building Production build
-- Performing Test HAVE_C_FLAG_O3
-- Performing Test HAVE_C_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Performing Test HAVE_CXX_FLAG_O3
-- Performing Test HAVE_CXX_FLAG_O3 - Success
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_C_FLAG_Wall
-- Performing Test HAVE_C_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Performing Test HAVE_CXX_FLAG_Wall
-- Performing Test HAVE_CXX_FLAG_Wall - Success
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_C_FLAG_Wunused_private_field
-- Performing Test HAVE_C_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_C_FLAG_fexceptions
-- Performing Test HAVE_C_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough - Success
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_C_FLAG_Wshadow
-- Performing Test HAVE_C_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_Wshadow
-- Performing Test HAVE_CXX_FLAG_Wshadow - Success
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init - Success
-- Configuring with CXX flag '-fno-extern-tls-init'
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Using GNU gold linker.
-- Disabling unit tests since assertions are disabled.
-- Found Python: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
-- Building GMP 6.2.1: /mnt/cvc5/build/deps/lib/libgmp.so
-- Looking for getc_unlocked
-- Looking for getc_unlocked - not found
-- Building CaDiCaL rel-1.5.2: /mnt/cvc5/build/deps/lib/libcadical.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Building CryptoMiniSat 5.8.0: /mnt/cvc5/build/deps/lib/libcryptominisat5.a
-- Building Poly 126147f1ceae9f771a68bad9cbc199cf96daec46: /mnt/cvc5/build/deps/lib/libpoly.so, /mnt/cvc5/build/deps/lib/libpolyxx.so
-- Building SymFPU: /mnt/cvc5/build/deps/include/
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS - Failed
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Python: /usr/include/python3.10 (found suitable exact version "3.10.6") found components: Development Development.Module Development.Embed 
-- Found PythonInterp: /usr/bin/python3.10 (found version "3.10.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.6") 
<string>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
-- Found Cython: /usr/bin/cython3 (Required is at least version "0.29") 
-- Performing Test HAVE_CXX_FLAGWerror
-- Performing Test HAVE_CXX_FLAGWerror - Success
-- Performing Test HAVE_CXX_FLAGWshadow
-- Performing Test HAVE_CXX_FLAGWshadow - Success
-- Performing Test HAVE_CXX_FLAGWimplicit_fallthrough
-- Performing Test HAVE_CXX_FLAGWimplicit_fallthrough - Success
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
_modinit_prefix:PyInit_
-- Downloading pythonic API: /mnt/cvc5/build/deps/src/CVC5PythonicAPI
Python bindings install command: /usr/bin/python3.10 /mnt/cvc5/build/src/api/python/setup.py install
          --prefix=/usr/local
          --single-version-externally-managed
          --record=cvc5-installed-files.txt

[1;34mcvc5 1.0.6-dev[m

[1;34mBuild profile             : [32mproduction[m

[1;34mAssertions                : [32moff[m
[1;34mDebug symbols             : [32moff[m
[1;34mDebug context mem mgr     : [32moff[m

[1;34mMuzzle                    : [32moff[m
[1;34mStatistics                : [32mon[m
[1;34mTracing                   : [32moff[m

[1;34mASan                      : [32moff[m
[1;34mUBSan                     : [32moff[m
[1;34mTSan                      : [32moff[m
[1;34mCoverage (gcov)           : [32moff[m
[1;34mProfiling (gprof)         : [32moff[m
[1;34mUnit tests                : [32moff[m
[1;34mValgrind                  : [32moff[m

[1;34mShared build              : [32mon[m
[1;34mPython bindings           : [32mon[m
[1;34mJava bindings             : [32moff[m
[1;34mInterprocedural opt.      : [32moff[m

[1;34mCryptoMiniSat             : [32mon (local)[m
[1;34mGLPK                      : [32moff[m
[1;34mKissat                    : [32moff[m
[1;34mLibPoly                   : [32mon (local)[m
[1;34mCoCoALib                  : [32moff[m
[1;34mMP library                : [32mgmp (local)[m
[1;34mEditline                  : [32moff[m

[1;34mApi docs                  : [32moff[m


[1;34mCPPLAGS (-D...): [32mNDEBUG CVC5_STATISTICS_ON CVC5_USE_CRYPTOMINISAT CVC5_USE_POLY[m
[1;34mCXXFLAGS       : [32m-O3 -Wall -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -fno-extern-tls-init -Wno-class-memaccess[m
[1;34mCFLAGS         : [32m-O3 -Wall -fexceptions -Wimplicit-fallthrough -Wshadow[m
[1;34mLinker flags   : [32m -fuse-ld=gold[m

[1;34mInstall prefix : [32m/usr/local[m

[1;34mcvc5 license:[m modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  To build against GPL'ed
libraries which can improve cvc5's performance on arithmetic and bit-vector
logics, use the 'configure.sh' script to re-configure with '--best --gpl'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/cvc5/build
```

</details>

**Comment by mpreiner** [comment] 2023-07-27 15:36
By default the logic used for the solver is set to `ALL`. Try to narrow down the logic you will use with the created solver and it should work: 
```
from cvc5.pythonic import SolverFor

s = SolverFor('QF_BV')`
s.setOption('bitblast', 'eager')
```

**Comment by ambiso** [comment] 2023-07-27 16:13
@mpreiner Thanks for the help! Unfortunately, this still results in the same issue for me:

```py
root@18c13f46bd63:/mnt# cat mre.py  
from cvc5.pythonic import SolverFor

s = SolverFor('QF_BV')
s.setOption('bitblast', 'eager')

print(s.check())

root@18c13f46bd63:/mnt# python3 mre.py 
Traceback (most recent call last):
  File "/mnt/mre.py", line 6, in <module>
    print(s.check())
  File "/usr/local/lib/python3.10/dist-packages/cvc5/pythonic/cvc5_pythonic.py", line 5313, in check
    r = CheckSatResult(self.solver.checkSatAssuming(*[a.ast for a in assumptions]))
  File "cvc5.pxi", line 1989, in cvc5_python_base.Solver.checkSatAssuming
RuntimeError: Error in option parsing: Eager bit-blasting currently does not support model generation for the combination of bit-vectors with arrays or uinterpreted functions. Try --bitblast=lazy
```

I can however confirm that this would seem to help if I was using an `smt2` file.
Copying this file: https://github.com/cvc5/cvc5/blob/b38e2611e5ef8ee05a67527fbaee475dc6cc79f9/test/regress/cli/regress3/bv_to_int_bench_9839.smt2.minimized.smt2#L1-L9

I can check it with `cvc5 --bitblast=eager bv_to_int_bench_9839.smt2.minimized.smt2` only if the `(set-logic QF_BV)` line is not commented out.

**Comment by mpreiner** [comment] 2023-08-08 15:58
Looks like this is an issue in the pythonic API, the following code works:

```
from cvc5 import Solver
s = Solver()
s.setLogic('QF_BV')
s.setOption('bitblast', 'eager')
print(s.checkSat())
```

**Comment by alex-ozdemir** [comment] 2023-08-08 18:16
Hi @ambiso. We're [working on this now](https://github.com/cvc5/cvc5_pythonic_api/pull/89) and will update you when the issue is fixed.

Thank you for reporting it.

**Comment by mpreiner** [comment] 2023-08-22 16:24
This should be fixed on main now.

**Closed by mpreiner** 2023-08-22 16:24 UTC
