### ISSUE TITLE
Failures with cadical-1.9.4

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#10266] opened 2024-01-08 17:22 UTC
**Describe the bug**

Two regression tests fail when cvc5 is linked with a debug build of cadical-1.9.3 or 1.9.4.
```
The following tests FAILED:
	1169 - regress0/prop/cadical_bug2.smt2 (Failed)
	1172 - regress0/prop/cadical_bug5.smt2 (Failed)
```

Both tests trigger an assertion failure in cadical when running `cvc5` with `--check-unsat-cores`:
```
> ./build/bin/cvc5 -i --sat-solver=cadical --check-unsat-cores test/regress/cli/regress0/prop/cadical_bug2.smt2 
sat
Assertion failed: (v.level >= real_level), function explain_external_propagations, file external_propagate.cpp, line 468.
Abort
```

This is because assumption literals are re-ordered by cadical. The activation literals may not be assigned by cadical before other assumed literals, even though activation literals are assumed first in cvc5.

**Comment by aniemetz** [comment] 2024-01-31 23:55
@BrunoDutertre thanks for reporting. We are currently in the process of ironing out issues with new versions of CaDiCaL, especially latest version 1.9.4. It is currently not yet clear who the culprit is, it seems that assumptions/invariants on our side do not match changed internal behavior (and thus assertions about interface behavior) of CaDiCaL (@arminbiere @kfazekas).

@mpreiner this is not the only assertion failure in CaDiCaL we get on regressions.

**Comment by aniemetz** [comment] 2024-02-01 17:43
I can confirm that these issues entirely due to option `ilb` being enabled by default.

**Comment by arminbiere** [comment] 2024-02-01 17:48
Does cvc5 require to have the assumptions to be internally assigned in the order given or do you think disabling ILB hides an issue in CaDiCaL?

**Comment by aniemetz** [comment] 2024-02-01 23:54
I don't think that we require this, but then I'm also not sure what is going on with ILB enabled. We'll try to get to the bottom of this.

**Comment by BrunoDutertre** [comment] 2024-02-02 17:31
From what I've seen, I don't think that's an issue in CaDiCaL The problem here is that  cvc5 starts theory propagation too early, before the  activation_literal is assigned in CaDiCaL, which can leads cvc5 to produce incorrect reason/explanation clauses later on (since every reason will include the activation_literal).

**Comment by aniemetz** [comment] 2024-03-11 21:52
CaDiCaL 1.9.4 has issues with ILB in combination with the external propagator. This will be fixed in an upcoming version 2.x. We are currently working with @kfazekas to iron out any remaining issues for this upcoming release.

On top of that, with 1.9.4 we see a severe performance regression compared to 1.7.4. We will thus not use 1.9.4 but immediately skip to the upcoming CaDiCaL version where all issues in combination with ILB are ironed out on both sides.

**Closed by aniemetz** 2024-03-11 21:52 UTC

**Comment by arminbiere** [comment] 2024-03-11 23:40
FYI, we have this interim release 1.9.5 which addresses performance issues, but waiting for the final upcoming major release is a good idea.
