### ISSUE TITLE
invalid model issue on a QF_FP instance

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#9972] opened 2023-08-22 18:39 UTC
Commit: https://github.com/cvc5/cvc5/releases/download/latest/cvc5-Linux-2023-08-22-7a4a17b

```
[567] % cvc5 --check-models small.smt2
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool) at /home/runner/work/cvc5/cvc5/src/smt/check_models.cpp:146
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (= #b00000000000000000000000000000000 ((_ fp.to_sbv 32) roundTowardZero b))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
[568] % cat small.smt2
(set-logic QF_FP)
(declare-const a Float64)
(declare-const b Float64)
(assert (= (_ bv0 32) ((_ fp.to_sbv 32) RTZ b)))
(assert (bvuge ((_ fp.to_sbv 32) RTZ a) (_ bv1 32)))
(check-sat)
```

**Comment by zhendongsu** [comment] 2023-11-04 07:38
Another instance:
```
[518] % cvc5 --check-models small.smt2 
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool) at /home/runner/work/cvc5/cvc5/src/smt/check_models.cpp:146
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (not (= #b00000000000000000000000000000000 (bvlshr ((_ extract 31 0) ((_ sign_extend 32) ((_ fp.to_sbv 32) roundTowardZero a))) ((_ extract 31 0) ((_ sign_extend 32) ((_ fp.to_sbv 32) roundTowardZero b))))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
[519] % cat small.smt2 
(set-logic QF_FP)
(declare-const a Float64)
(declare-const b Float64)
(assert (not (= (_ bv0 32) (bvlshr ((_ extract 31 0) ((_ sign_extend 32) ((_ fp.to_sbv 32) RTZ a))) ((_ extract 31 0) ((_ sign_extend 32) ((_ fp.to_sbv 32) RTZ b)))))))
(check-sat)
```

**Comment by martin-cs** [comment] 2023-11-19 15:52
I think the first one of these may well be a duplicate of 9854

**Closed** 2024-04-05 18:44 UTC
