### ISSUE TITLE
Fatal failure at src/expr/node_builder.cpp:278

### ISSUE THREAD

**Issue by fwangdo** [cvc5/cvc5#9638] opened 2023-03-30 11:41 UTC
Greetings,
For this instance, a crash bug occurred. Sincerely hope that this instance would be helpful for cvc5 team.
We tried to reduce an instance that triggered the bug however, it was not reduced that much. 
Since it's too long to write the instance in this article, we'll attach this instance.
[qflia_crash.txt](https://github.com/cvc5/cvc5/files/11110970/qflia_crash.txt)
(we used ./configure.sh --auto-download --assertions)

```
$ ./cvc5 ./small.smt2 --produce-interpolants
Fatal failure within void cvc5::internal::NodeBuilder::realloc(size_t) at /cvc5-ec83110/src/expr/node_builder.cpp:278
Check failure

 toSize > d_nvMaxChildren
attempt to realloc() a NodeBuilder to a smaller/equal size!
Aborted (core dumped)
```

cvc5 version/commit: [ec83110](https://github.com/cvc5/cvc5/commit/ec8311076290485f88e8fb1037a5ebba8bf2ed04)
Operating system: Ubuntu 20.04

**Comment by ajreynol** [comment] 2023-03-30 15:18
I think this is a duplicate of https://github.com/cvc5/cvc5/issues/9126?

**Comment by fwangdo** [comment] 2023-03-30 15:23
As you mentioned, It looks very similar to #9126. I will move this issue to #9126.

**Closed** 2023-03-31 01:46 UTC
Labels: duplicate
