### ISSUE TITLE
Incorrect resolution proof

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9393] opened 2023-01-10 00:37 UTC
**Describe the bug**

I'm on the `proof-new` branch (commit 4235ba0344e857ac178b2a11d94b9d7efebc0967).
On the following input file, cvc5 generates an incorrect alethe proof. 
```
(set-logic QF_UF)
(declare-sort I 0)
(declare-fun o (I I) I)
(declare-fun e4 () I)
(declare-fun e2 () I)
(declare-fun e () I)
(assert (and (or (= e4 (o e4 e)) (= e4 (o e4 e4)) (= e4 (o e4 e2))) (or (= (o e4 e4) (o (o e4 e2) e2)) (= (o e4 e) (o (o e4 e2) e2))) (or (= e2 (o e4 e)) (= e2 (o e4 e4)) (= e2 (o e4 (o (o e4 e2) e2)))) (= (o e4 e2) (o e (o (o e4 e2) e2))) (or (= e4 (o (o (o e4 e2) e2) (o e4 e2))) (= e4 (o e (o (o e4 e2) e2))) (= e4 (o (o e4 e2) e))) (or (= e (o e4 e4)) (= e2 (o e4 e2)))))
(assert (and (not (= (o e4 e4) (o (o e4 e2) e4))) (not (= (o e2 e4) (o (o e4 e2) e4)))))
(assert (and (= (o e4 e2) (o e4 (o e4 e2))) (= (o e4 e2) (o (o (o e4 e2) e2) (o e4 e2)))))
(check-sat)
```

The bad proof step is t211 below. 
```
(step t208
      (cl (= e2 (o e4 (o (o e4 e2) e2))) (not (= e4 (o e4 e))) (not (= (o e4 e) (o (o e4 e2) e2))) (not (= e2 (o e4 e4))))
      :rule reordering :premises (t207))
(step t209
      (cl (= e2 (o e4 e)) (= e2 (o e4 e4)) (= e2 (o e4 (o (o e4 e2) e2))))
      :rule or :premises (t87))
(step t210
      (cl (not (= e4 (o e (o (o e4 e2) e2)))))
      :rule resolution :premises (t165 t174 t146) :args ((= (o e4 e4) (o (o e4 e2) e4)) true (= (o e4 e2) (o e (o (o e4 e2) e2))) false))
(step t211
      (cl (= e2 (o e4 (o (o e4 e2) e2))) (not (= e4 (o e4 e))) (not (= (o e4 e) (o (o e4 e2) e2))) (= e2 (o e4 e)) (= e2 (o e4 (o (o e4 e2) e2))))
      :rule resolution
      :premises (t208 t209 t210)
      :args ((= e2 (o e4 e4)) false  (= e4 (o e (o (o e4 e2) e2))) true))
```
This step is wrong because pivot `(= e4 (o e (o (o e4 e2) e2)))` occurs in only one of the three premises.

The bug seems to be in `eliminateCrowdingLits` of `proof_post_processor.cpp`. 
The proof is fine when disabling `--opt-res-reconstruction-size`.

To reproduce:
```
cvc5 --dump-proofs --proof-format=alethe --dag-thresh=0 --simplification=none --proof-granularity=theory-rewrite --proof-alethe-res-pivots test.smt2
```
Then proof checking fails:
```
carcara check bad-proof.txt test.smt2 --skip-unknown-rules
[ERROR] checking failed on step 't211' with rule 'resolution': pivot was not found in clause: '(= e4 (o e (o (o e4 e2) e2)))'
invalid
```

**Comment by HanielB** [comment] 2023-01-11 22:05
Thanks for the report! I have fixed the issue at the proof-new branch. I'll try to merge into main soon (as with the Alethe backend features). Since we do not yet have [carcara](https://github.com/ufmg-smite/carcara) integrated into our regressions we cannot properly reproduce this test yet, but the regression will be included for when we do.

**Closed by HanielB** 2023-01-11 22:05 UTC
