### ISSUE TITLE
Fatal failure at /cvc5/src/theory/theory_model_builder.cpp:1087

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8954] opened 2022-07-12 01:23 UTC
Hi,
For this instance, cvc5 https://github.com/cvc5/cvc5/commit/3c3a730c70623001c93751759aee3ab2b3d6fb07
```
$ cvc5 -q small.smt2
Fatal failure within bool cvc5::internal::theory::TheoryEngineModelBuilder::buildModel(cvc5::internal::theory::TheoryModel*) at /cvc5/src/theory/theory_model_builder.cpp:1087
Check failure

 false

Aborted (core dumped)
$ cat small.smt2
(declare-const x Int)
(declare-fun e () (Bag Int))
(declare-fun ex () (Bag Int))
(assert (or (exists ((v Bool)) (= 1 (+ 0 (bag.card (bag.difference_subtract ex e))))) (forall ((V String)) (= (bag.card ex) (* x (bag.card ex))))))
(check-sat)
```

**Comment by aniemetz** [comment] 2022-08-23 23:21
This might be a duplicate of https://github.com/cvc5/cvc5-projects/issues/507.

**Comment by mudathirmahgoub** [comment] 2022-08-24 13:42
Yes it is a duplicate and fixed by PR https://github.com/cvc5/cvc5/pull/8433

**Closed by mudathirmahgoub** 2022-08-24 13:42 UTC
