### ISSUE TITLE
Fatal failure on problem mixing arrays and floating points

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9858] opened 2023-06-27 18:18 UTC
**Describe the bug**

cvc5 crashes on this example:
```
(set-logic ALL)
(define-sort S16 () Float64)
(define-sort S37 () (Array S16 Int))
(declare-const c S37)
(assert (= 0 (select c (fp.min (fp (_ bv0 1) (_ bv0 11) (_ bv0 52)) (fp (_ bv1 1) (_ bv0 11) (_ bv0 52))))))
(check-sat)
```
In debug mode, I get this error:
```
Fatal failure within cvc5::internal::Node cvc5::internal::theory::fp::FpWordBlaster::getValue(cvc5::internal::theory::Valuation &, cvc5::internal::TNode) at ..../cvc5/src/theory/fp/fp_word_blaster.cpp:1302
Check failure

 t.isRoundingMode() || t.isFloatingPoint()
Asking for the value of a type that is not managed by the floating-point theory
Abort
```
In a non-debug build, the error is different:
```
(error "Illegal argument detected
cvc5::internal::theory::TheoryId cvc5::internal::theory::kindToTheoryId(cvc5::internal::Kind)

  `k' is a bad argument
bad kind")
```

This happens with a recent build: 1bd2dc23cfd22836af45ea9c34f09fecd8f05ab0.

This seems related to #9752 and #5094.

**Comment by aniemetz** [comment] 2023-07-02 08:01
This seems to be related to / a duplicate of https://github.com/cvc5/cvc5-projects/issues/648.

**Closed** 2023-07-02 15:32 UTC

**Comment by BrunoDutertre** [comment] 2023-07-03 23:20
It's still crashing on a variant of this example. I'll open another issue.
