### ISSUE TITLE
Fatal failure at /src/prop/minisat/core/Solver.cc:1994

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8410] opened 2022-03-27 03:08 UTC
Hi,
For this instance, cvc5https://github.com/cvc5/cvc5/commit/c7507cebfa909d6662b7a8635a9dc9e3f2bf801a debug build
```
# cvc5 -i -q delta.smt2
(error "argument type is not a subtype of the function's argument type:
argument:  (+ (- 1) delta_9 (* (- 1) toInt_3))
has type:  Real
not subtype: Int
in term : (SKOLEM_FUN_MOD_BY_ZERO_5 (+ (- 1) delta_9 (* (- 1) toInt_3)))")
Fatal failure within void cvc5::Minisat::Solver::pop() at /root/cvc5/src/prop/minisat/core/Solver.cc:1994
Check failure

 decisionLevel() == 0

Aborted (core dumped)
# cat delta.smt2
(push)
(assert (or (forall ((v Real)) (or (exists ((V Real)) (or (exists ((V Real)) (= 0 (mod (to_int v) (to_int (- v)))))))))))
(check-sat)
```

**Comment by mpreiner** [comment] 2022-03-28 16:08
Probably a duplicate of https://github.com/cvc5/cvc5-projects/issues/435

**Comment by ajreynol** [comment] 2022-03-29 20:20
The assertion failure is indeed the same as the other issue.

However, perhaps by coincidence, the regression in this issue should not throw an exception in the first place. It is due to subtyping in CEGQI, I will submit a fix shortly.

**Closed** 2022-03-30 18:06 UTC
