### ISSUE TITLE
Refutation unsoundness or Fatal failure at src/smt/solver_engine.cpp:1428 (nightly build)

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#7948] opened 2022-01-14 17:09 UTC
```
[558] % cvc5-2022-01-14-x86_64-Linux-production -q --check-unsat-cores small.smt2
Fatal failure within void cvc5::SolverEngine::checkUnsatCore() at /buildbot/ubuntu20-amd64-production/build/src/smt/solver_engine.cpp:1428
Internal error detected SolverEngine::checkUnsatCore(): produced core was satisfiable.
Aborted
[559] % cat small.smt2 
(assert (<= (cos (* (cos (- 3.0)) 0.5)) 1.0))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-02-04 18:33
An empty unsat core is returned, this suggests a soundness issue in the NL transcendental solver.

**Comment by zhendongsu** [comment] 2022-02-05 23:44
Another instance:
```
[524] % cvc5 -q --check-unsat-cores small.smt2 
Fatal failure within void cvc5::SolverEngine::checkUnsatCore() at /local/suz-local/software/CVC4/src/smt/solver_engine.cpp:1428
Internal error detected SolverEngine::checkUnsatCore(): produced core was satisfiable.
Aborted
[525] % cat small.smt2 
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= a 0))
(assert (= b (cos a)))
(check-sat)
```

**Comment by zhendongsu** [comment] 2022-02-12 14:06
Combing the two asserts in the instance above leads to a refutation unsoundness issue:
```
[527] % cvc5 -q small.smt2 
sat
[528] % cvc5 -q --check-unsat-cores small.smt2 
unsat
[529] % cat small.smt2 
(declare-fun a () Real)
(declare-fun b () Real)
(assert (and (= a 0) (= b (cos a))))
(check-sat)
```

**Comment by ajreynol** [comment] 2022-02-17 18:44
The use of `check-unsat-cores` in these examples imply `simplification=none`, which is required for making the benchmarks not trivially solved.

The unsoundness is caused by incorrectly assigning a concavity region to the argument of `sin` terms.

**Comment by ajreynol** [comment] 2022-02-24 20:03
The first benchmark times out on master.
The latter 2 benchmarks can be solved with simplification, but time out on master.
Thus, closing the issue.

**Closed by ajreynol** 2022-02-24 20:03 UTC
