### ISSUE TITLE
Invalide unsat core for separation logic formula

### ISSUE THREAD

**Issue by rainoftime** [cvc5/cvc5#5607] opened 2020-12-05 15:27 UTC
Hi, for the following formula,
cvc4 a3395c1
~~~~
(declare-fun v4 () Bool)
(declare-heap (Int Int))
(assert (wand true true))
(check-sat)
(assert (pto 1 0))
(check-sat)

./cvc4 -q -i --check-unsat-cores ../delta.out.smt2 
sat
Fatal failure within void CVC4::SmtEngine::checkUnsatCore() at /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1464
Internal error detectedSmtEngine::checkUnsatCore(): produced core was satisfiable.
Aborted
~~~~

**Comment by HanielB** [comment] 2020-12-07 17:24
As an internal note, this works on proof-new. When we start using it for unsat-cores we will close this issue.

**Comment by 4tXJ7f** [comment] 2021-05-28 01:34
@HanielB Just tested this on master and it is still an issue with the new unsat core modes (all of them).

**Comment by ajreynol** [comment] 2021-11-03 23:49
The issue still occurs at https://github.com/cvc5/cvc5/commits/master.  Separation logic does not work properly with incremental currently, which is likely the root cause of this.

**Closed** 2022-01-06 23:26 UTC
