### ISSUE TITLE
(--re-inter-mode=all) Fatal failure at src/theory/strings/regexp_operation.cpp:699

### ISSUE THREAD

**Issue by wintered** [cvc5/cvc5#9050] opened 2022-08-16 20:16 UTC
```
$cvc5 -q --re-inter-mode=all --strings-exp bug.smt2                                
Fatal failure within cvc5::internal::Node cvc5::internal::theory::strings::RegExpOpr::derivativeSingle(cvc5::internal::Node, cvc5::internal::String) at /local/windomin/bin/solvers/CVC4/src/theory/strings/regexp_operation.cpp:699
Unreachable code reached                                                           
[1]    3645728 abort      cvc5 -q --re-inter-mode=all --strings-exp bug.smt2       
$cat bug.smt2                                                                      
(declare-fun a () String)                                                          
(declare-fun b () String)                                                          
(assert (str.in_re (str.++ (ite (str.in_re b (re.* (re.range "a" "u")))            
(str.substr a 0 0) "B") b) (re.++ (re.range "a" "u")                               
(re.diff (re.* re.allchar) (str.to_re "")))))                                      
(check-sat)                                                                        
$  
```

**Comment by ajreynol** [comment] 2022-08-19 16:48
Duplicate of https://github.com/cvc5/cvc5/issues/9040.

**Closed by ajreynol** 2022-08-19 16:48 UTC
Labels: duplicate
