### ISSUE TITLE
Crash on a problem with floating-points and arrays

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9752] opened 2023-05-17 22:21 UTC
**Describe the bug**

cvc5 has a fatal failure on the following input:
```
(set-logic ALL)
(define-sort FP () (_ FloatingPoint 8 24))
(declare-const c17 Real)
(declare-const c62 (_ BitVec 1))
(define-fun t107 () FP (fp #b0 #b00000000 #b00000000000000000000000))
(define-fun t110 () FP (fp #b0 #b00000000 #b00000000000000111111100))
(declare-const c137 (Array FP Real))
(define-fun t223 () FP ((_ to_fp 8 24) roundNearestTiesToEven c62))
(define-fun t428 () FP (fp.fma roundNearestTiesToAway t107 t110 t223))
(assert (not (= c17 (select c137 t428))))
(check-sat)
(exit)
```

Here's the error:
```
Fatal failure within cvc5::internal::Node cvc5::internal::theory::fp::FpWordBlaster::getValue(cvc5::internal::theory::Valuation &, cvc5::internal::TNode) at  .../cvc5/src/theory/fp/fp_word_blaster.cpp:1294
Check failure

 Theory::isLeafOf(var, THEORY_FP)

Abort
```

This happens when cvc5 is built in debug mode. I'm using c52df9d14b48a09a1b5810f2a3fe656a366dfe0b.

**Comment by mpreiner** [comment] 2023-05-22 16:01
Looks like a duplicate of #5094.

**Comment by BrunoDutertre** [comment] 2023-05-26 16:10
Are floating-point bugs ever fixed?

**Closed** 2023-06-23 20:13 UTC
Labels: duplicate
